Neos:
  Flow:
    mvc:
      routes:
        'Sitegeist.Archaeopteryx':
          position: 'before Neos.Neos'
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Sitegeist.Archaeopteryx:ApiControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Sitegeist\Archaeopteryx\Application\.*\Controller\.*Controller'
